export { default as HomePage } from './website/HomePage'
export { default as NotfoundPage } from './website/NotfoundPage'
export { default as DashboardPage } from './admin/DashboardPage'
export {default as CategoryList} from './admin/CategoryList'
export {default as AddCategory} from './admin/AddCategory'
export {default as EditCategory} from './admin/EditCategory'